"""Validate retained raw proofs and their exact metadata-only revalidation."""
import json,sys
from pathlib import Path
F=Path('/Users/frank/mygit/Tablekeeper/factory');sys.path.insert(0,str(F))
from factorykit.common import canonical,digest,load_config,write_json,utc_now,artifact_path
R=F.parent/'runs/run6-preparation-20261004';P=R/'permissions';c=load_config(R/'factory.yaml');ch=digest(canonical(c));sh=digest(artifact_path(c,'source_lock'));audit=json.loads((P/'configuration-revalidation.json').read_text());original=audit['original_probe_configuration_sha256'];assert audit['current_configuration_sha256']==ch
history=json.loads((R/'source-lock-history.json').read_text());original_lock=history['previous_scoped_lock_sha256'];assert history['current_scoped_lock_sha256']==sh and audit['source_lock_sha256']==original_lock
run=json.loads((P/'probe-input-audit.json').read_text());paths={s['phase']:Path(s['evidence']) for s in run['steps']};data={k:json.loads(p.read_text()) for k,p in paths.items()}
for k,v in data.items():
 assert v['configuration_sha256']==original and v['source_lock_sha256']==original_lock,(k,'unexpecteddrift')
 if k!='assigned':assert v['command_exec']['exitCode']==0 and not v.get('error'),k
q=data['quick']['checks'];assert q['workspace_write']=='PASS' and q['git_commit']['status']=='PASS' and q['loopback_bind']=='PASS'
assert all(q[x]['request_succeeded'] for x in ('pypi','npm')) and q['files_pythonhosted_download']['status']=='PASS'
assert not q['blocked_external']['request_succeeded'] and q['outside_workspace_write']['status']=='DENIED' and q['exact_docker_socket']=='PASS' and q['docker_version']['exit_code']==0 and data['quick']['thread_turn_count']==0
ac=data['assigned']['checks'];assert data['assigned']['status']=='PASS' and ac['entries_before']==ac['entries_after']==['.git'] and not ac['git_status'] and ac['ls_remote_exit']==0 and ac['branch_matches'] and ac['remote_matches'] and not ac['local_HEAD_exists'] and ac['object_store_unchanged']
assert data['build']['checks']['docker_build']['exit_code']==0
b=data['browser']['checks']['docker_browser'];bi=json.loads(b['stdout']);assert b['exit_code']==0 and bi['status']=='PASS' and bi['click_result']=='1' and bi['container_outbound']['status']=='DENIED'
cl=data['cleanup']['checks'];assert cl['container_check']['exit_code']==1 and 'No such container' in cl['container_check']['stderr'] and cl['image_remove']['exit_code']==0
assert json.loads((P/'subscription-auth.json').read_text())['status']=='PASS' and json.loads((P/'subscription-auth.json').read_text())['configuration_sha256']==ch
ref=lambda p:dict(path=str(p.resolve()),sha256=digest(p))
limits=['Preparation-only zero-model diagnostic evidence; no BAND Agent, model turn, room message, application implementation or product acceptance.', 'Budget approved=false and copied global/room terminal halts remain unchanged; successful probes do not authorize any worker or launch.', 'Git ls-remote checked the configured private branch without fetching objects or creating commits; judged checkout remains .git-only and HEAD unborn.', 'Exact approved Docker socket grants daemon access; diagnostic browser container separately used network none, dropped capabilities, no host mounts and no-new-privileges.', 'Raw proof hashes and timestamps retained. Only launch.submission_open_verified changed false to true after the raw probes, based on fresh authenticated submission access; adapter permission fields are byte-equivalent. The scoped lock was separately reconciled only for SDK scratch trust, preserving challenge/docs; source-lock-history.json records old/new bindings. Earlier Run5-to-Run6 global drift remains unclassified. The four new generic mandate paragraphs do not change command/exec permissions and have separate static review only; no new model behavior is established. Later config/source changes require fresh reconciliation.']
s={'status':'PASS_PERMISSION_PREPARATION_ONLY','observed_at':data['cleanup']['observed_at'],'revalidated_at':utc_now(),'configuration_sha256':ch,'original_probe_configuration_sha256':original,'source_lock_sha256':sh,'original_probe_source_lock_sha256':original_lock,'source_lock_reconciliation':ref(R/'source-lock-history.json'),'model_turns':0,'room_messages':0,'budget_approved':c['budgets']['approved'],'configured_model':c['runtime']['model'],'model_changed':False,'scope':'Actual PM judged Codex adapter command/exec, assigned empty checkout, canonical private-origin ls-remote, neutral scratch Git/network/socket, Docker build and constrained Chromium','evidence':{k:ref(p) for k,p in paths.items()},'additional_evidence':{k:ref(P/k) for k in ('subscription-auth.json','model-discovery.json','probe-input-audit.json','configuration-revalidation.json')},'limitations':limits}
write_json(P/'summary.json',s)
obs=[]
for name,keys in {'permissions_agent_write_git':['assigned','quick'],'permissions_docker_build':['quick','build','cleanup'],'permissions_browser':['browser','cleanup'],'permissions_development_network':['quick','assigned']}.items():obs.append({'id':name,'status':'PASS','observed':True,'observed_at':s['observed_at'],'observer':'Codex preparation operator using actual maintained BAND Codex adapter command/exec','scope':s['scope'],'evidence':[*(ref(paths[k]) for k in keys),ref(P/'summary.json'),ref(P/'configuration-revalidation.json'),ref(R/'source-lock-history.json')],'revalidation':ref(P/'configuration-revalidation.json'),'limitations':limits})
write_json(P/'permission-observations.json',{'created_at':utc_now(),'configuration_sha256':ch,'source_lock_sha256':sh,'observations':obs,'scope':'Importable four permission entries only; main readiness state and original observations unchanged'})
print(json.dumps({'status':s['status'],'configuration_sha256':ch,'source_lock_sha256':sh,'summary':str(P/'summary.json'),'summary_sha256':digest(P/'summary.json'),'auth':'PASS','git_objects_unchanged':ac['object_store_unchanged'],'remote_branch_present':bool(ac['ls_remote_stdout'].strip()),'budget_approved':s['budget_approved'],'global_config_sha256':digest(Path.home()/'.codex/config.toml')}))
